All features added
Simpleshaikh1/hello_rails_react pull request #3
Opened 2023-11-27 21:32 UTC by Simpleshaikh1

Create a new Rails app called 'hello-rails-react'.
Use the command rails new -j webpack my_new_rails_app as described in the previous lesson's tutorial.
Verify that the jsbundling-rails gem is added to your Gemfile.
Initialize your project with Git.
Install needed node dependencies as described in the previous lesson's tutorial.
Create a babel.config.js in the root folder of your project as described in the previous lesson's tutorial.
Update webpack.config.js to include the babel loader as described in the previous lesson's tutorial.
Make sure that your project has a Postgres database set up.
Create a table for storing your messages and create 5 different greetings.
Create an API endpoint that selects a random greeting from your table (you will need a controller with an action and Rails route).
Create a static view that will be the root of your app.
Create the App component with react-router and render it in your static view.
Create the Greeting component that will display a greeting. Set it up as a route in your App component.
Create a store, an action, and a reducer that will connect to your API endpoint to get the random greeting.
Display the random greeting in your Greeting component.

2023-11-27 22:20 UTC, tresorsawasawa reviewed
# STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @Simpleshaikh1 ,:wave: :wave: 
While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 🛑 🛑

You have submitted a project that doesn't run. Make sure you fix all the issues and your app can run.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

---
Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

---
_Invalid Code Review Request **Does not count** into the code reviews limit._

2023-11-28 10:00 UTC, Olamarx requested changes
Hi @Simpleshaikh1, 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media3.giphy.com/media/LuRH8UGQTPEx2lafrD/giphy-downsized-medium.gif"/>

## Highlights
- Linters passed ✔️
- Readme file professional ✔️
- Commit messages meaningful ✔️
- API works ✔️
- Gitflow used ✔️

## Required Changes ♻️
_Check the comments under the review._
- [ ] I am making this comment here because the package.json file is merged. The comment is that react-dom and babel-loader should be part of the dependencies, it means you have not yet added react library and it can't definitely show what is not added, kindly add it too. To prove that your project does not have react at all, the image I circled below shows that react is not featured in the app and that is why it is not on
![image](https://github.com/Simpleshaikh1/hello_rails_react/assets/86200356/e8986efd-dc13-4242-9e26-2b003cc37d91)
And for GitHub that uses react, you can see in the image below that it is on 
![image](https://github.com/Simpleshaikh1/hello_rails_react/assets/86200356/2d505743-f109-4ec2-9859-8ce7a2182369)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-28 10:00 UTC, Olamarx commented on app/controllers/api/greetings_controller.rb
> +    render json: { greeting: @greeting.greeting }
- [ ] I see you added `.greeting` to your "greeting, but there is no greeting object in your seed data, but content, I would encourage you to change it to content or return the whole greeting like that, at the moment, the error below is what I get until I removed the `.greeting`.
![image](https://github.com/Simpleshaikh1/hello_rails_react/assets/86200356/026bab64-360e-45f7-b404-56ad404e88a7)

2023-11-28 15:23 UTC, brainconnect93 approved these changes
## Status: Approved :heavy_check_mark:

Hi @Simpleshaikh1, 👋 👋  

Your project is complete! Great job for following the project requirement🥇and implementing the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 


<img src="https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif" width="600px" height="300px">

## Good Points 👍

- Descriptive Pull Request title & summary. ✔️
- "Hello world" project with `react-rails` gem ✔️
- Implement the `API` in the backend correctly ✔️
- Implement the front end correctly ✔️ 
- Good use of Git flow ✔️

## Optional changes

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brainconnect93 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-28 20:15 UTC, merged